name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install  # If you have npm dependencies
          # Replace with your build command if necessary (e.g., npm run build)
          # Example: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/* .
          touch .nojekyll  # Create .nojekyll file if your site uses JavaScript
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git push -f origin gh-pages

