name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy
        run: |
          npm install  # Replace with your build command if necessary
          npm run build  # Replace with your build command if necessary

          mkdir deploy
          cp -r !(deploy) deploy  # Copy all files except 'deploy' directory itself

          cd deploy
          git init
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://github.com/yourusername/repositoryname.git master:gh-pages
